version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    network_mode: "host"
    ports:
    - "8866:8866"
    environment:
      PRISMA_CONFIG: |
        port: 8866
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: localhost
            port: '5432'
            database: Prisma
            schema: fonicart
            user: syed
            password: syed1989
            ssl: false
            migrations: true